#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-fill ~/rc/wallpapers/mae_goreintake.jpg
/usr/lib/polkit-kde-authentication-agent-1 &
picom &
unclutter &
polybar main &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config focused_border_color  "#e42a8d"
bspc config border_width          1
bspc config window_gap            1
bspc config top_padding           22

bspc config single_monocle        true  # no border if there is only one node
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a '*:*:Picture-in-Picture' state=floating sticky=on rectangle=560x315+1360+765
